// カテゴリと内容で解析し内容をTableとして解析(Transformerを使用)
?start            :root
root              : config+
config            : "[" category_name "]\n" contents?
category_name     : /[^\]]+/
contents          : line_space_row+
line_space_row    : (value " "?)+ "\n"
value             : EMPTY_STRING| "\"" ESCAPED_STRING "\"" | SIGNED_NUMBER | FLOAT
SIGNED_NUMBER     : /\-?[0-9]+/
%import common.FLOAT
ESCAPED_STRING    :  /((\^")|[^"])+/
EMPTY_STRING      : "\"\""
